# This is a basic workflow to help you get started with Actions

name: SSH Deploy

# Controls when the action will run. 
on:
    # Triggers the workflow on push or pull request events but only for the current branch
    pull_request:
    push:
      branches:
        - account

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    deploy:
      runs-on: ubuntu-latest  
      
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        # Runs a single command using the runners shell
        - name: SSH Deploy
          uses: easingthemes/ssh-deploy@v2.1.4
          env:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
            REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
            REMOTE_USER: ${{ secrets.DEPLOY_USER }}
            REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
            SOURCE: "docs/"
            TARGET: ${{ secrets.DEPLOY_TARGET }}
