# This is a basic workflow to help you get started with Actions

name: CI/CD to github pages

# Controls when the action will run. 
on:
    # Triggers the workflow on push or pull request events but only for the current branch
    push:
      branches:
        - ver2_dev

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
      name: Test and deploy to gh-pages 
      runs-on: ubuntu-latest
      
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      
        # Checks-out repository branch ver2_dev
        - uses: actions/checkout@v2
          with:
            ref: 'gh-pages'


        - name: Removing files that can cause merge conflict
          uses: EndBug/add-and-commit@v7.0.0
          with:
            remove: './docs -r'
            branch: 'gh-pages'
            message: 'Removing files that can cause merge conflict'
        
        - name: Merge development -> gh-pages
          uses: devmasx/merge-branch@v1.3.1
          with:
            type: now
            from_branch: ver2_dev
            target_branch: gh-pages
            github_token: ${{ github.token }}
        
        # Set up Python 3.6 environment
        - uses: actions/setup-python@v2
          with:
              python-version: '3.x'
              
        # Install dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Initialize db
          run: |
            python src/flask_se.py init
        # Run Flask Frozen
        - name: Run Flask Frozen to build /docs/
          run: |
            python src/flask_se.py build
            
        - run: ls
            
        # install npm and run script
        - name: install npm and run script
          uses: actions/setup-node@v2
          with: 
            node-version: '14'

        - run: npm install fast-glob
        - run: npm install imagemin imagemin-webp
        - run: npm install @nodelib/fs.stat
        - run: npm install @nodelib/fs.walk
        - run: npm install @nodelib/fs.scandir
        - run: npm init --yes
        #- run: node ./WebpConverter.js
        - run: npm i -g purgecss
        - run: purgecss --css docs/assets/css/*.css --content docs/*.html --content docs/master/*.html --content docs/bachelor/*.html --content docs/department/*.html --safelist show --output docs/assets/css

        # Commit docs to gh-pages
        - name: Push to gh-pages
          uses: EndBug/add-and-commit@v7.0.0
          with:
            add: '.'
            remove: './node_modules -r'
            branch: 'gh-pages'
            message: 'Update gh-pages /docs/'
