# This is a basic workflow to help you get started with Actions

name: CI/CD to github pages

# Controls when the action will run. 
on:
    # Triggers the workflow on push or pull request events but only for the current branch
    push:
      branches:
        - ver2_dev

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
      name: Test and deploy to gh-pages 
      runs-on: ubuntu-latest
      
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      
        # Checks-out to branch ver2_dev
        - uses: actions/checkout@v2
          with:
            ref: 'ver2_dev'
            
        - uses: dawidd6/action-delete-branch@v3
          with:
            github_token: ${{github.token}}
            branches: gh-pages
        
        - uses: peterjgrainger/action-create-branch@v2.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            branch: 'gh-pages'
        
        # Checks-out repository branch ver2_dev
        - uses: actions/checkout@v2
          with:
            ref: 'gh-pages'
            
        
        # Set up Python 3.6 environment
        - uses: actions/setup-python@v2
          with:
              python-version: '3.x'
              
        # Install dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        # Run Flask Frozen
        - name: Run Flask Frozen to build /docs/
          run: |
            python src/flask_se.py build

        # Commit docs to gh-pages
        - name: Push to gh-pages
          uses: Automattic/action-commit-to-branch@master
          with:
            branch: 'gh-pages'
            commit_message: 'Update gh-pages /docs/'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
