on:
  schedule:
    - cron:  '*/1 * * * *'
jobs:
  ping:
    runs-on: ubuntu-18.04
    steps:

      - name: curl actuator
        id: ping
        run: |
          echo "::set-output name=status::$(curl -s -o /dev/null -w "%{http_code}" ${{secrets.HOST}})"
      - name: health check
        run: |
          if [[ ${{ steps.ping.outputs.status }} != *"200"* ]]; then
            echo "health check is failed"
            exit 1
          fi
          echo "It's OK"
      - name: send alert in telegram
        if: ${{ failure() }}
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              Health check of the:
              ${{secrets.HOST}}
              failed with the result:
              ${{ steps.ping.outputs.status }}